---
- name: Ansible Playbook to iterate over a loop using with_items directly
  hosts: local
  tasks:
   - name: Download modules 
     homebrew:
       name: "{{ item }}"
       state: present
     with_items:
        - httpd
        - openssl
        - java
        - nvm

