---
- name: Manage services
  hosts: local
  tasks:
  - name: Stop the httpd service if running
    service:
      name: httpd
      state: started
    when: ansible_distribution == "Debian"
      
      

