---
- name: Ansible Playbook to create docker container
  hosts: local
  tasks:
    - name: Install requests module
      pip:
        name: requests
        state: present
    - name: get nginx docker image 
      ansible.builtin.docker_image:
        source: pull
        name: nginx:latest
    - name: run docker container
      ansible.builtin.docker_container:
        name: nginx-test
        image: nginx:latest
        state: started
        ports: 
          - "8080:80"
      
