---
- name: Ansible Playbook to download nginx module
  hosts: local
  tasks:
   - name: Get a Nginx module 
     homebrew:
       name: "{{ item }}"
       state: present
     with_items:
        - httpd
        - openssl
        - java
        - nvm

